
 <ul class='section__main__listView2' id='listView'>

<li>
    <div>
        <div style='width: 32px;float: left;'><img src="<?php echo $this->url->get('img/star1.png') ?>" alt='star'></div>
        <div><a href='#'>
                <h2>Daily Question for You</h2>
            </a></div>
    </div>
</li>

<?php

    $starImg = $this->url->get('img/star1.png');

    

    foreach($questions as $question){
        // echo "<h1>$question[question]</h1>
        echo "
            <li>
                <div class='addQueProfileView'>
                    <div style='float: left;'>
                        <p>Question added - </p>
                    </div>
                    <div>
                        <p>Machine Learning</p>
                    </div>
                    
                </div>
                <h1 class='queTitle2'>$question[question]</h1>
                <div class='addQueProfileView'>
                    <div style='float: left;'>
                        <p>No answer yet - </p>
                    </div>
                    <div>
                        <p>Last followed 7m ago</p>
                    </div>
                </div>
                <div class='bottomControll'>
                    <div class='ans-btn'>
                        <div style='float: left;'> <a href='/timeline/question/detail/$question[id]'> <svg width='24px' height='24px' viewBox='0 0 24 24' version='1.1'
                                xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'>
                                <g id='pass' stroke='none' fill='none' fill-rule='evenodd'>
                                    <g id='pen' transform='translate(11.485281, 12.485281) rotate(-315.000000) translate(-11.485281, -12.485281) translate(9.485281, 2.485281)'>
                                        <path d='M0,7.51471863 L2.22044605e-16,1.99994543 C8.67738547e-17,0.895375929 0.8954305,-5.45711382e-05 2,-5.45711382e-05 C3.1045695,-5.45711382e-05 4,0.895375929 4,1.99994543 L4,7.51471863 M4,12.5147186 L4,16 L2.00256278,20 L0,16 L0,12.5147186'
                                            id='Rectangle-5' class='icon_svg-stroke' stroke='#666' stroke-width='1.5'
                                            stroke-linecap='square' stroke-linejoin='round'></path>
                                        <polygon id='pen_tip' class='icon_svg-fill_as_stroke' fill='#666' transform='translate(2.000000, 18.750000) scale(1, -1) translate(-2.000000, -18.750000) '
                                            points='2 17.5 3.25 20 0.75 20'></polygon>
                                    </g>
                                    <path d='M4.63603897,5.63603897 L18.5,19.5' id='Line' class='icon_svg-stroke' stroke='#666'
                                        stroke-width='1.5' stroke-linecap='round'></path>
                                </g>
                            </svg>  
                        </div> 
                        <span>Read more</span></a>
                    </div>
                </div>
            </li>
            
      
                    
            
        ";
    }

?>

</ul>




